name: Frontend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Save SSH key
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Install Node.js and npm if missing
            if ! command -v npm &> /dev/null
            then
              sudo apt update
              sudo apt install -y nodejs npm
            fi

            # Clone repo if not exists, otherwise pull latest changes
            if [ ! -d "computexx" ]; then
              git clone https://github.com/1O1manu/computexx.git
            else
              cd computexx
              git reset --hard
              git pull origin main
            fi

            # Go into repo folder
            cd computexx/ComputexFrontend

            # Install dependencies
            npm install

            # Start app in background on all interfaces
            nohup npm start -- --host 0.0.0.0 > app.log 2>&1 &
          EOF
